ActiveStorage で画像アップロードを実装しました。
kaiyu-archive/fjord-books_app pull request #8
Opened 2021-08-21 03:36 UTC by kaiyu-tech

課題「ActiveStorage で画像アップロードを実装する」の成果物です。
ご確認のほどよろしくお願いいたします。

2021-08-26 04:18 UTC, komagata requested changes

2021-08-26 04:18 UTC, komagata commented on app/views/users/index.html.erb
> +          <td><%= image_tag user.avatar.variant(resize: "100x100") if user.avatar.attached? %></td>
上の行にifがあるのでこちらに付ける必要はないかも？

2021-08-26 09:17 UTC, kaiyu-tech commented on app/views/users/index.html.erb
> +          <td><%= image_tag user.avatar.variant(resize: "100x100") if user.avatar.attached? %></td>
ご指摘ありがとうございます！
コードを修正した時に削除し忘れていました。

2021-08-29 04:18 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-09-05 01:51 UTC, merged